version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend
    volumes:
      - "./frontend/dist:/var/www/html"
      - "./frontend/nginx/default.conf:/etc/nginx/sites-available/default"
    
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    # persist info.json data
    volumes:
      - "./backend/info.json:/usr/src/app/backend/info.json"
    ports:
      - "8080:8080"
