version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5800:5800"
    restart: always
    depends_on:
      - backend
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    # persist info.json data
    volumes:
      - "./backend/info.json:/usr/src/app/backend/info.json"
    ports:
      - "8080:8080"
    restart: always




