FROM node:alpine

RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/backend

WORKDIR /usr/src/app/backend

COPY package*.json ./
RUN npm install
RUN npm ci --omit=dev

COPY . .

EXPOSE 8080

STOPSIGNAL SIGTERM

CMD ["npm","start"]